/**
 * MyApp Rest APIs
 * APIs for MyApp.
 *
 * OpenAPI spec version: 1.0
 * Contact: test@emaildomain.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrderProductDto } from './orderProductDto';

export interface OrderForm {
    address: string;
    address2: string;
    city: string;
    email: string;
    firstName: string;
    lastName: string;
    orderProducts: Array<OrderProductDto>;
    phoneNo: string;
    postalCode: string;
    saveAddress: boolean;
    totalPrice: string;
}
