/**
 * MyApp Rest APIs
 * APIs for MyApp.
 *
 * OpenAPI spec version: 1.0
 * Contact: test@emaildomain.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Role { 
    id?: number;
    name?: Role.NameEnum;
}
export namespace Role {
    export type NameEnum = 'ROLE_ADMIN' | 'ROLE_USER';
    export const NameEnum = {
        ADMIN: 'ROLE_ADMIN' as NameEnum,
        USER: 'ROLE_USER' as NameEnum
    };
}