/**
 * MyApp Rest APIs
 * APIs for MyApp.
 *
 * OpenAPI spec version: 1.0
 * Contact: test@emaildomain.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Order } from './order';
import { ProductItem } from './productItem';
import { Role } from './role';
import { UserInfo } from './userInfo';
import { UserMetadata } from './userMetadata';

export interface User { 
    cartProducts?: Array<ProductItem>;
    email: string;
    favoriteProducts?: Array<ProductItem>;
    id?: number;
    orderList?: Array<Order>;
    password: string;
    roles?: Array<Role>;
    userInfo?: UserInfo;
    userMetadata?: UserMetadata;
    username: string;
}