export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './basicErrorController.service';
import { BasicErrorControllerService } from './basicErrorController.service';
export * from './orderController.service';
import { OrderControllerService } from './orderController.service';
export * from './productController.service';
import { ProductControllerService } from './productController.service';
export * from './ratingSystemController.service';
import { RatingSystemControllerService } from './ratingSystemController.service';
export * from './resourceController.service';
import { ResourceControllerService } from './resourceController.service';
export * from './servertest.service';
import { ServertestService } from './servertest.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [AuthControllerService, BasicErrorControllerService, OrderControllerService, ProductControllerService, RatingSystemControllerService, ResourceControllerService, ServertestService, UserControllerService];
